apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: BlockchainNodeStatuses
  labels:
    app: blockchain-node-statuses
    environment: Development
    tier: Service
  name: blockchain-node-statuses
  namespace: tools
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-node-statuses
  template:
    metadata:
      labels:
        app: blockchain-node-statuses
      name: blockchain-node-statuses
    spec:
      containers:
      - name: blockchain-node-statuses
        image: docker.io/swisschains/tools-blockchain-node-statuses:dev
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: RemoteSettingsUrls__0 
          value: "http://settings.common.svc.cluster.local/common"
        - name: RemoteSettingsUrls__1 
          value: "http://settings.common.svc.cluster.local/tools/common"
        - name: RemoteSettingsUrls__2
          value: "http://settings.common.svc.cluster.local/tools/blockchain-node-statuses"