apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockchain-node-statuses
    environment: Development
  name: blockchain-node-statuses
  namespace: tools
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: blockchain-node-statuses
  sessionAffinity: None
  type: ClusterIP
